select page.id as page_id, page_page_attributes.attribute as page_page_attributes_attribute, page_page_attributes.author as page_page_attributes_author, page_page_attributes.comment as page_page_attributes_comment, page_page_attributes.date as page_page_attributes_date, page_page_attributes.id as page_page_attributes_id, page_page_attributes.value as page_page_attributes_value, page_page_attributes.version as page_page_attributes_version, page.path as page_path, page_template.id as page_template_id, page_template.name as page_template_name, page_template_template_attributes.attribute as page_template_template_attributes_attribute, page_template_template_attributes.author as page_template_template_attributes_author, page_template_template_attributes.comment as page_template_template_attributes_comment, page_template_template_attributes.date as page_template_template_attributes_date, page_template_template_attributes.id as page_template_template_attributes_id, page_template_template_attributes.value as page_template_template_attributes_value, page_template_template_attributes.version as page_template_template_attributes_version,  1=1 
from page left join page_attribute page_page_attributes on page_page_attributes.page_id = page.id left join template page_template on page_template.id = page.template_id left join template_attribute page_template_template_attributes on page_template_template_attributes.template_id = page_template.id 

left join (select page_id as __page_id, attribute as __attribute, max(version) as __max_version from page_attribute group by attribute, page_id) __pa on (__pa.__page_id = page_id and __pa.__attribute = page_page_attributes.attribute) 
left join (select template_id as __template_id, attribute as __attribute, max(version) as __max_version from template_attribute group by attribute, template_id )  __ta on (__ta.__template_id = page.template_id and __ta.__attribute = page_template_template_attributes.attribute) 
where 1=1   and ( page.path = '/index.html')
and (page_page_attributes.version is null or page_page_attributes.version = __pa.__max_version)
and (page_template_template_attributes.version is null or page_template_template_attributes.version = __ta.__max_version)

select page.id as page_id, page_page_attributes.attribute as page_page_attributes_attribute, page_page_attributes.author as page_page_attributes_author, page_page_attributes.comment as page_page_attributes_comment, page_page_attributes.date as page_page_attributes_date, page_page_attributes.id as page_page_attributes_id, page_page_attributes.value as page_page_attributes_value, page_page_attributes.version as page_page_attributes_version, page.path as page_path, page_template.id as page_template_id, page_template.name as page_template_name, page_template_template_attributes.attribute as page_template_template_attributes_attribute, page_template_template_attributes.author as page_template_template_attributes_author, page_template_template_attributes.comment as page_template_template_attributes_comment, page_template_template_attributes.date as page_template_template_attributes_date, page_template_template_attributes.id as page_template_template_attributes_id, page_template_template_attributes.value as page_template_template_attributes_value, page_template_template_attributes.version as page_template_template_attributes_version,  1=1 
from page left join page_attribute page_page_attributes on page_page_attributes.page_id = page.id left join template page_template on page_template.id = page.template_id left join template_attribute page_template_template_attributes on page_template_template_attributes.template_id = page_template.id join (select page_id as __page_id, attribute as __attribute, max(version) as __max_version from page_attribute group by attribute, page_id) __pa on (__pa.__page_id = page_id and __pa.__attribute = page_page_attributes.attribute) join (select template_id as __template_id, attribute as __attribute, max(version) as __max_version from template_attribute group by attribute, template_id) __ta on (__ta.__template_id = page.template_id and __ta.__attribute = page_template_template_attributes.attribute) where 1=1  and (page_page_attributes.version is null or page_page_attributes.version = __pa.__max_version) and (page_template_template_attributes.version is null or page_template_template_attributes.version = __ta.__max_version)   and ( page.path = '/hakkimizda.html')